repos:
-   repo: https://github.com/ambv/black
    rev: 22.1.0
    hooks:
    -   id: black
        language_version: python3.8

-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0  # Use the ref you want to point at
    hooks:
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-merge-conflict
    -   id: check-case-conflict
    -   id: end-of-file-fixer
    -   id: check-json
    -   id: check-xml
    -   id: check-yaml
    -   id: check-toml
    -   id: mixed-line-ending
        args: ['--fix=lf']
        description: Forces line endings to the UNIX LF character

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.931'
    hooks:
    -   id: mypy
        args:
          [
            --namespace-packages,
            --ignore-missing-imports,
            --disallow-any-generics,
            --disallow-any-explicit,
            --disallow-untyped-calls,
            --disallow-untyped-defs,
            --disallow-incomplete-defs,
            --disallow-untyped-decorators,
            --no-implicit-optional,
            --warn-redundant-casts,
            --warn-unreachable,
            --local-partial-types,
            --strict-equality,
            --show-error-context,
            --show-column-numbers,
            --show-error-codes,
            --pretty
          ]

-   repo: https://github.com/PyCQA/pylint
    rev: 'v2.12.2'
    hooks:
    -   id: pylint
        name: pylint
        entry: pylint
        language: system
        types: [python]
        args:
          [
                # "-rn", # only display messages
                # "-sn", # don't display the score
                "--rcfile=.pylintrc", # link to config file
          ]
